:sparkles: add FHIR resource validation endpoint that receives a POST…
srdc/tofhir pull request #141
Opened 2023-12-12 12:13 UTC by YemreGurses

… request to validate the FHIR resources using the onFHIR or FHIR validator based on a given redirectUrl parameter

Fixes: https://github.com/srdc/tofhir/issues/137

2023-12-12 13:07 UTC, dogukan10 requested changes
Can you add a test for this endpoint ? 
**Update: _It's added._**

2023-12-12 13:13 UTC, YemreGurses commented on tofhir-server/src/main/scala/io/tofhir/server/endpoint/FhirDefinitionsEndpoint.scala
> +      parameters("redirectUrl") { redirectUrl =>
Works for me

2023-12-13 12:52 UTC, dogukan10 commented on tofhir-server/src/main/scala/io/tofhir/server/endpoint/FhirDefinitionsEndpoint.scala
> +    } ~ pathPrefix(SEGMENT_VALIDATE) {
I think we can put it under pathPrefix(SEGMENT_FHIR_DEFINITIONS). WDYT @YemreGurses  ?

2023-12-13 14:08 UTC, dogukan10 requested changes

2023-12-13 14:08 UTC, dogukan10 commented on tofhir-server/src/main/scala/io/tofhir/server/endpoint/FhirDefinitionsEndpoint.scala
> +   * Validates a FHIR resource using the onFHIR or FHIR validator (it is given as a parameter as redirectUrl)
It should be **fhirValidationUrl**

2023-12-13 14:08 UTC, dogukan10 commented on tofhir-server/src/main/scala/io/tofhir/server/service/FhirDefinitionsService.scala
> +   * Redirects the request to the onFHIR/FHIR validator based on the given redirectUrl and returns the response.
It should be **fhirValidationUrl**

2023-12-13 14:39 UTC, dogukan10 commented on tofhir-server/src/main/scala/io/tofhir/server/endpoint/FhirDefinitionsEndpoint.scala
> +    } ~ pathPrefix(SEGMENT_VALIDATE) {
We decided to leave it as it is

2023-12-13 14:44 UTC, dogukan10 approved these changes

2023-12-13 14:52 UTC, merged