Multiple mapping task with same mapping url
srdc/tofhir pull request #224
Opened 2024-09-11 07:48 UTC by Okanmercan99

2024-09-18 12:22 UTC, Okanmercan99 commented
![image](https://github.com/user-attachments/assets/5f4b6077-7940-40ec-ac3f-d71bb1e3727e)
For this update, you should add a `name` field for each `mappingTask`. There should be no duplicate `mappingTask` names in a job definition, otherwise, `tofhir` will throw an error at the start.

2024-09-20 08:19 UTC, dogukan10 requested changes

2024-09-20 08:19 UTC, dogukan10 commented on tofhir-engine/src/main/scala/io/tofhir/engine/util/FhirMappingJobFormatter.scala
> +      throw new MappingException("Duplicate 'name' fields found in the MappingTasks within the MappingJob! Ensure each MappingTask has a unique name.")
Add the duplicate name to the message.

2024-09-20 08:19 UTC, dogukan10 commented on tofhir-engine/src/main/scala/io/tofhir/engine/model/FhirMappingTask.scala
> +  final val TXT_TSV = "txt-tsv"
Let's remove this.

2024-09-20 08:19 UTC, dogukan10 commented on tofhir-engine/src/main/scala/io/tofhir/engine/model/FhirMappingJob.scala
> +      throw new BadRequestException("Duplicate mappingTask name. Ensure each MappingTask has a unique name!")
Add the duplicate name.

2024-09-20 08:19 UTC, dogukan10 commented on tofhir-engine/src/main/scala/io/tofhir/engine/mapping/MappingTaskExecutor.scala
> +              mappingTaskName = mappingTaskName,
Previously, we were using `fhirMappingService.mappingUrl`, which is no longer in use. Can we replace `mappingUrl` with `mappingTaskName` in`fhirMappingService` and continue using it without modifying the method arguments, such as `executeMappingOnInput`?

2024-09-20 08:19 UTC, dogukan10 commented on tofhir-engine/src/main/scala/io/tofhir/engine/mapping/job/FhirMappingJobManager.scala
> +                  projectId: Option[String] = None,
Comma is redundant.

2024-09-20 12:02 UTC, dogukan10 approved these changes

2024-09-20 12:59 UTC, merged