Refactor file format to content type
srdc/tofhir pull request #226
Opened 2024-09-18 09:13 UTC by Okanmercan99

2024-09-18 12:24 UTC, Okanmercan99 commented
![image](https://github.com/user-attachments/assets/f1cb82ae-3c0f-46b4-bd1f-e5ddea78e1cb)
For this update, you should change the `fileFormat` field to `contentType`. Additionally, you should add the `contentType` field to all `FileSystemSource` entries.

2024-09-18 12:28 UTC, Okanmercan99 commented
![image](https://github.com/user-attachments/assets/66c0a1af-0491-42ed-bedd-3be55fbdf006)
You should add the `contentType` field to all `sinkSettings` that are `FileSystemSinkSettings`.

2024-09-20 10:42 UTC, dogukan10 commented
I believe that `contentType` should be optional. In most cases, such as the example below, specifying `contentType` is redundant because the file extension (e.g., `.csv`) already indicates the content type:

```json
"sourceBinding": {
  "source": {
    "jsonClass": "FileSystemSource",
    "path": "patients.csv",
    "contentType": "csv",
    "sourceRef": "pilot1-source"
  }
}
```

The use of `contentType` should be limited to scenarios where a file extension can represent multiple content types. For instance, a `.txt` file could contain either CSV or NDJSON data, so in that case, `contentType` would clarify the format (e.g., `csv` or `ndjson`) while reading the file.

WDYT @YemreGurses, shall we make it optional ?

2024-09-23 06:41 UTC, dogukan10 requested changes

2024-09-23 10:56 UTC, dogukan10 approved these changes

2024-09-23 11:53 UTC, merged